// leave off @2x/@3x
const images = {
  
  background: require('../Images/background.jpg'),
  loginForm: require('../Images/bg.png'),
  button: require('../Images/btn.png'),
  bottomBar: require('../Images/bottomBar.png'),
  triangle: require('../Images/triangle.png'),
  check: require('../Images/check.png'),
  flag_ru: require('../Images/ru.png'),
  flag_eng: require('../Images/eng.png'),
  flag_he: require('../Images/he.png'),
  flag_esp: require('../Images/esp.png'),
  flag_fr: require('../Images/fr.png'),
  flag_it: require('../Images/it.png'),
  flag_de: require('../Images/de.png'),
  icon1: require('../Images/icon1.png'),
  icon2: require('../Images/icon2.png'),
  icon3: require('../Images/icon3.png'),
  icon4: require('../Images/icon4.png'),
  dog: require('../Images/dog.png'),
  exit: require('../Images/Exit.png'),
  arrow_sjop: require('../Images/ArrowSjop.png'),
  back_arrow: require('../Images/BackArrow.png'),
  big_shop_ellipse: require('../Images/BigShopEllipse.png'),
  button_scan_code: require('../Images/ButtonScanCode.png'),
  coil_back_arrow: require('../Images/CoilBackArrow.png'),
  ear_right: require('../Images/EarRight-2.png'),
  ear_left: require('../Images/EarRight.png'),
  photo_button: require('../Images/PhotoButton.png'),
  photo_icon: require('../Images/PhotoIcon.png'),
  barcode_icon: require('../Images/ScanCodeIcon.png'),
  shop_ellipse: require('../Images/ShopEllipse.png'),
  placeholder: require('../Images/placeholder.png'),
  cog_black: require('../Images/GajkaBlack.png'),
  cog_green: require('../Images/GajkaGreen.png'),
  pixel_cat: require('../Images/PixelCat.png'),
  left_arrow: require('../Images/LeftBlackArrow.png'),
  right_arrow: require('../Images/RightBlackArrow.png'),
  grey_line: require('../Images/GreyLine.png'),
  green_button: require('../Images/GreenButton.png'),
  confirm_button: require('../Images/confirm_btn.png'),
  icons: require('../Images/icons.png'),
  categoryBoard: require('../Images/categoryBoard.png'),
  plus: require('../Images/plus.png'),
  leftArrow: require('../Images/leftArrow.png'),
  cancel: require('../Images/Cancel.png'),
  whiteArrow: require('../Images/whiteArrow.png'),
  greenCheck: require('../Images/greenCheck.png'),
  checkBox: require('../Images/checkBox.png'),
  greenLeft: require('../Images/greenLeft.png'),
  greenDown: require('../Images/greenDown.png'),
}

export default images
